@domain = localhost:8080
@userToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI1ZjJkNzc3NjI3MzY1YmM1MTY3ZGNkODIiLCJpYXQiOjE1OTY4MTUyMzR9.H5Olylo2PdzhNMS-CcSH5onBMYvMJf78bMwA22-oO3A
@username = mooselliot3
@organisationHandle = organisationA

POST http://{{domain}}/users/
Content-Type: application/json

{
    "username": "{{username}}",
    "fullName": "Elliot Koh",
    "email": "kyzelliot2@gmail.com",
    "password": "12345" 
}
