@postId = 5f434ebeb804eeaf33c8d36c
@username = mooselliot
@userToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI1ZjJkNzc3NjI3MzY1YmM1MTY3ZGNkODIiLCJpYXQiOjE1OTY4MTUyMzR9.H5Olylo2PdzhNMS-CcSH5onBMYvMJf78bMwA22-oO3A
#Make post
POST http://localhost:8080/posts
Content-Type: application/json
Authorization: Bearer {{userToken}}

{
    "content": "Hello world! I am making another last post just because I want to test out whether a different length post would allow for larger post area and also whether the parameters are correct because I want to see the post type too",
    "postType": "Testimony"
}

### Get post
GET http://localhost:8080/posts/{{postId}}
Content-Type: application/json
Authorization: Bearer {{userToken}}

### Comment on post
POST http://localhost:8080/posts/{{postId}}/comment
Content-Type: application/json
Authorization: Bearer {{userToken}}

{
    "comment": "Yo this is lit!! 🔥"
}

### Get comments
GET http://localhost:8080/posts/{{postId}}/comments
Content-Type: application/json
Authorization: Bearer {{userToken}}

### React to post
POST http://localhost:8080/posts/{{postId}}/react
Content-Type: application/json
Authorization: Bearer {{userToken}}

{
    "reactionType": "like"
}

### unreact to post
POST http://localhost:8080/posts/{{postId}}/unreact
Content-Type: application/json
Authorization: Bearer {{userToken}}

{
    "reactionType": "like"
}

### Get user posts by id
GET http://localhost:8080/users/{{username}}/posts
Content-Type: application/json
Authorization: Bearer {{userToken}}

### Get user feed
GET http://localhost:8080/feed?limit=5
Content-Type: application/json
Authorization: Bearer {{userToken}}


