POST http://localhost:8080/user/create
Content-Type: application/json

{
    "username": "mooselliot",
    "fullName": "Elliot Koh",
    "email": "kyzelliot@gmail.com",
    "password": "12345"
}

### 
POST http://localhost:8080/user/login
Content-Type: application/json

{
    "username": "mooselliot",
    "password": "12345"
}

###
# Create Organisation
POST http://localhost:8080/organisation/create
Content-Type: application/json

{
    "handle": "organisationA",
    "name": "Organisation A",
    "contact": "64001234",
    "address": "Aljunied Ave 4, S342232"
}

###
# Join Organisation
POST http://localhost:8080/organisation/organisationA/userJoin
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI1ZjJkNzc3NjI3MzY1YmM1MTY3ZGNkODIiLCJpYXQiOjE1OTY4MTUyMzR9.H5Olylo2PdzhNMS-CcSH5onBMYvMJf78bMwA22-oO3A

###
# Leave Organisation
POST http://localhost:8080/organisation/organisationA/userLeave
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI1ZjJkNzc3NjI3MzY1YmM1MTY3ZGNkODIiLCJpYXQiOjE1OTY4MTUyMzR9.H5Olylo2PdzhNMS-CcSH5onBMYvMJf78bMwA22-oO3A

###
# Get Organisation Members
GET http://localhost:8080/organisation/organisationA/members
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI1ZjJkNzc3NjI3MzY1YmM1MTY3ZGNkODIiLCJpYXQiOjE1OTY4MTUyMzR9.H5Olylo2PdzhNMS-CcSH5onBMYvMJf78bMwA22-oO3A

# eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI1ZjJjYzFiNDRiN2RlN2E4YTk2MWRjZTMiLCJpYXQiOjE1OTY3NjkyMDh9.orBEsXJjZ8HOFMlF18EqcEBgKjuTqHZGrqgprCqbTBM