@userToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI1ZjJkNzc3NjI3MzY1YmM1MTY3ZGNkODIiLCJpYXQiOjE1OTY4MTUyMzR9.H5Olylo2PdzhNMS-CcSH5onBMYvMJf78bMwA22-oO3A
@username = mooselliot
@organisationHandle = organisationA

POST http://localhost:8080/users/create
Content-Type: application/json

{
    "username": "mooselliot",
    "fullName": "Elliot Koh",
    "email": "kyzelliot@gmail.com",
    "password": "12345"
}

### 
POST http://localhost:8080/users/login
Content-Type: application/json

{
    "username": "mooselliot",
    "password": "12345"
}

### GET user profile
GET http://localhost:8080/users/{{username}}
Content-Type: application/json
Authorization: Bearer {{userToken}}

###
# Create Organisation
POST http://localhost:8080/organisations/create
Content-Type: application/json

{
    "handle": "organisationA",
    "name": "Organisation A",
    "contact": "64001234",
    "address": "Aljunied Ave 4, S342232"
}

###
# Join Organisation
POST http://localhost:8080/organisations/{{organisationHandle}}/userJoin
Content-Type: application/json
Authorization: Bearer {{userToken}}

###
# Leave Organisation
POST http://localhost:8080/organisations/{{organisationHandle}}/userLeave
Content-Type: application/json
Authorization: Bearer {{userToken}}

###
# Get Organisation Members
GET http://localhost:8080/organisations/{{organisationHandle}}/members
Content-Type: application/json
Authorization: Bearer {{userToken}}

### follow user
POST http://localhost:8080/users/{{username}}/follow
Content-Type: application/json
Authorization: Bearer {{userToken}}


